### ISSUE TITLE
Create Player Character

### ISSUE THREAD

**Issue by LiamDHealey** [Unicorn-Ranch-Studio/Syrup#2]
Player character should be able to walk, plant, and interact.

**Comment by Hexrin** [comment]
![Image](https://user-images.githubusercontent.com/71273371/174512800-228435a0-33a7-4b43-9cf0-d3e94ab7abb2.jpg)

**Comment by LiamDHealey** [comment]
New player character [wiki page](https://github.com/Unicorn-Ranch-Studio/Planting-Syrup/wiki/Player-Character) detailing control scheme.
