### ISSUE TITLE
Create Player Character Model

### ISSUE THREAD

**Issue by LiamDHealey** [Unicorn-Ranch-Studio/Syrup#49]
Create the player character model. Current WIP version of the model is pined in the #general chat in discord.
60cm tall.

![image](https://user-images.githubusercontent.com/56327428/174514804-b26b81ea-1399-495b-a45c-69a600f8c781.png)

![image](https://user-images.githubusercontent.com/56327428/174514785-0bcae5d2-cce8-4e32-a556-dc001303ae2c.png)

**Comment by Orionicles** [comment]
### 9/6/22, ON
Worked on head of Syrup, unhappy with shaping, possibly due to trying too hard for woodpecker-esque shaping. Will communicate with @LiamDHealey on thoughts soon.
